services:
  auth-be:
    ports:
      - "18080:8080"

  core-be:
    ports:
      - "18081:8081"

  admin-be:
    ports:
      - "18082:8082"

  bidding-ws:
    ports:
      - "18083:8080"

  auth-fe:
    ports:
      - "13000:3000"

  core-fe:
    ports:
      - "13001:3000"

  admin-fe:
    ports:
      - "13002:3000"
