#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
SELECT 'CREATE DATABASE ${AUTH_DATABASE_NAME}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${AUTH_DATABASE_NAME}')\gexec
SELECT 'CREATE DATABASE ${CORE_DATABASE_NAME}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${CORE_DATABASE_NAME}')\gexec
SQL

